app = "society-api-yourname"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "mcr.microsoft.com/dotnet/sdk:7.0"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    port = 443
