name: Build & Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Configure flyctl auth token
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN

      - name: Deploy to Fly
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          flyctl secrets set ConnectionStrings__DefaultConnection="$CONNECTION_STRING" Jwt__Key="$JWT_KEY" Jwt__Issuer="$JWT_ISSUER"
          flyctl deploy --config fly.toml --remote-only
